[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

# Completely skip broken test/certora files
fs_permissions = [{ access = "read", path = "./" }]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

